version: '3.9'

services:
  db:
    image: mysql
    container_name: ll7shopapi-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - 3306:3306